### ISSUE TITLE
unable to add window android view viewrootimpl permission denied

### ISSUE THREAD

**Issue by gitsuraj** [cinder92/react-native-audio-floating-widget#4]
I have added permission code in onCreate and override onActivityResult but still having permission denied error. Any idea 

![image](https://user-images.githubusercontent.com/3623281/44320566-1fbf3e00-a486-11e8-9c57-920831e44c6b.png)

**Comment by lucioflaviodev** [comment]
Help plss!!

**Comment by gitsuraj** [comment]
Hello @lucioflaviodev, I also had same issue running this, turns out there is some update in android which is causing this issue. I used following code to get permission for that. But again I had to recreate widget following code form this repo. Hopefully it helps.

`public static final int CODE_DRAW_OVER_OTHER_APP_PERMISSION = 2084;
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && !Settings.canDrawOverlays(this)) {
      askPermissions();
    }
}

void askPermissions(){
    Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
            Uri.parse("package:" + getPackageName()));
    startActivityForResult(intent, CODE_DRAW_OVER_OTHER_APP_PERMISSION);
  }

 @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data) {
 if(resultCode == CODE_DRAW_OVER_OTHER_APP_PERMISSION){
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && !Settings.canDrawOverlays(this)) {
            askPermissions();
      }else {
        //start aplication
      }
    }else{
      super.onActivityResult(requestCode, resultCode, data);
    }
  }`

**Comment by troyam** [comment]
Can you help me with this? I'm stucking with the same problem.
